<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConsoleMessageIdl.proto

namespace GPBMetadata;

class ConsoleMessageIdl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87020a17436f6e736f6c654d65737361676549646c2e70726f746f121b" .
            "636f6d2e627974726565732e636861742e77732e6d657373616765227b0a" .
            "10576562536f636b65744d65737361676512100a08636c69656e74496418" .
            "0120012803123d0a0b6d6573736167655479706518022001280e32282e63" .
            "6f6d2e627974726565732e636861742e77732e6d6573736167652e4d6573" .
            "736167655479706512160a0e6d657373616765436f6e74656e7418032001" .
            "28092a330a0b4d65737361676554797065120b0a07554e4b4e4f574e1000" .
            "120a0a06535452494e471001120b0a074a534f4e4f424a10024215421357" .
            "6562536f636b65744d65737361676549646c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

