<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConsoleMessageIdl.proto

namespace GPBMetadata;

class ConsoleMessageIdl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a86010a17436f6e736f6c654d65737361676549646c2e70726f746f121b" .
            "636f6d2e627974726565732e636861742e77732e6d65737361676522310a" .
            "0e436f6e736f6c654d657373616765120e0a067573657249641801200128" .
            "03120f0a076d65737361676518022001280942134211436f6e736f6c654d" .
            "65737361676549646c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

