<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebSocketMessageIdl.proto

namespace GPBMetadata;

class WebSocketMessageIdl
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89020a19576562536f636b65744d65737361676549646c2e70726f746f" .
            "121b636f6d2e627974726565732e636861742e77732e6d65737361676522" .
            "7b0a10576562536f636b65744d65737361676512100a08636c69656e7449" .
            "64180120012803123d0a0b6d6573736167655479706518022001280e3228" .
            "2e636f6d2e627974726565732e636861742e77732e6d6573736167652e4d" .
            "6573736167655479706512160a0e6d657373616765436f6e74656e741803" .
            "200128092a330a0b4d65737361676554797065120b0a07554e4b4e4f574e" .
            "1000120a0a06535452494e471001120b0a074a534f4e4f424a1002421542" .
            "13576562536f636b65744d65737361676549646c620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

