<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConsoleMessageIdl.proto

namespace Com\Bytrees\Chat\Ws\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.bytrees.chat.ws.message.WebSocketMessage</code>
 */
class WebSocketMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     */
    private $clientId = 0;
    /**
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     */
    private $messageType = 0;
    /**
     * Generated from protobuf field <code>string messageContent = 3;</code>
     */
    private $messageContent = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $clientId
     *     @type int $messageType
     *     @type string $messageContent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ConsoleMessageIdl::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     * @return int|string
     */
    public function getClientId()
    {
        return $this->clientId;
    }

    /**
     * Generated from protobuf field <code>int64 clientId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkInt64($var);
        $this->clientId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->messageType;
    }

    /**
     * Generated from protobuf field <code>.com.bytrees.chat.ws.message.MessageType messageType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Com\Bytrees\Chat\Ws\Message\MessageType::class);
        $this->messageType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string messageContent = 3;</code>
     * @return string
     */
    public function getMessageContent()
    {
        return $this->messageContent;
    }

    /**
     * Generated from protobuf field <code>string messageContent = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->messageContent = $var;

        return $this;
    }

}

